In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("analysis_with_surface_clusters.csv")
df

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
0,20230807,Canada Masters,Hard,False,Ben Shelton,Carlos Alcaraz,1410.848961,1864.117346,0,-453.268385,2,2,0.065831,0
1,20230814,Cincinnati Masters,Hard,False,Max Purcell,Carlos Alcaraz,1432.599522,1846.423679,0,-413.824157,2,2,0.081017,0
2,20230828,Us Open,Hard,True,Bernabe Zapata Miralles,Novak Djokovic,1458.760979,1857.668601,0,-398.907621,1,2,0.016258,0
3,20230828,Us Open,Hard,True,Lloyd Harris,Carlos Alcaraz,1464.366432,1852.334845,0,-387.968413,2,2,0.019206,0
4,20230828,Us Open,Hard,True,Alexandre Muller,Novak Djokovic,1481.946315,1860.411504,0,-378.465190,1,2,0.019847,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2867,20230828,Us Open,Hard,True,Carlos Alcaraz,Daniel Evans,1848.794448,1499.381908,1,349.412541,2,0,0.974764,1
2868,20230703,Wimbledon,Grass,True,Carlos Alcaraz,Matteo Berrettini,1846.751562,1495.784060,1,350.967502,2,0,0.975141,1
2869,20230927,Beijing,Hard,False,Alexander Zverev,Diego Schwartzman,1771.926817,1415.766524,1,356.160293,2,1,0.888360,1
2870,20230703,Wimbledon,Grass,True,Carlos Alcaraz,Jeremy Chardy,1854.290733,1467.385701,1,386.905031,2,1,0.980071,1
2871,20231123,Davis Cup Finals QF: SRB vs GBR,Hard,False,Novak Djokovic,Cameron Norrie,1915.192397,1513.517233,1,401.675164,2,2,0.900394,1

## See all rows where prediction went wrong

In [3]:
df_filtered = df[df['player_A_win'] != df['predict_R']].sort_values(by='predict_proba_R', ascending=False)
df_filtered.tail(10)

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
55,20231016,Tokyo,Hard,False,Shintaro Mochizuki,Taylor Fritz,1454.326910,1684.068809,1,-229.741900,0,2,0.181630,0
54,20231016,Tokyo,Hard,False,Jordan Thompson,Alexander Zverev,1525.971046,1756.178309,1,-230.207263,0,2,0.181238,0
30,20230807,Canada Masters,Hard,False,Marcos Giron,Holger Rune,1471.700428,1732.899961,1,-261.199533,2,2,0.173354,0
163,20230703,Wimbledon,Grass,True,Daniel Elahi Galan,Yoshihito Nishioka,1385.238609,1534.969629,1,-149.731020,2,2,0.172723,0
20,20230508,Rome Masters,Clay,False,Fabian Marozsan,Carlos Alcaraz,1500.037942,1783.473071,1,-283.435130,1,1,0.165435,0
26,20230807,Canada Masters,Hard,False,Tommy Paul,Carlos Alcaraz,1599.815682,1871.224406,1,-271.408724,2,2,0.165204,0
31,20231002,Shanghai Masters,Hard,False,Diego Schwartzman,Taylor Fritz,1430.020839,1691.123998,1,-261.103159,1,2,0.164867,0
13,20230724,Hamburg,Clay,False,Daniel Altmaier,Andrey Rublev,1446.236069,1742.110979,1,-295.874910,1,1,0.155912,0
53,20230529,Roland Garros,Clay,True,Daniel Altmaier,Jannik Sinner,1458.158735,1690.906010,1,-232.747274,1,1,0.089383,0
18,20230529,Roland Garros,Clay,True,Thiago Seyboth Wild,Daniil Medvedev,1500.000000,1791.985524,1,-291.985524,1,1,0.051678,0

In [4]:
upsets_df = df_filtered[df_filtered['predict_R'] == 1]
upsets_df

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
2764,20230828,Us Open,Hard,True,Holger Rune,Roberto Carballes Baena,1686.954083,1511.102677,0,175.851407,2,0,0.873220,1
2747,20230828,Us Open,Hard,True,Stefanos Tsitsipas,Dominic Stricker,1674.578378,1508.546623,0,166.031756,2,0,0.862022,1
2759,20230828,Us Open,Hard,True,Frances Tiafoe,Ben Shelton,1647.788745,1473.055673,0,174.733072,2,2,0.839809,1
2739,20230703,Wimbledon,Grass,True,Casper Ruud,Liam Broady,1634.402412,1472.958745,0,161.443666,2,2,0.821242,1
2732,20230828,Us Open,Hard,True,Tommy Paul,Ben Shelton,1654.007825,1495.021856,0,158.985969,2,2,0.817630,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1709,20230916,Davis Cup Finals RR: SRB vs CZE,Hard,False,Dusan Lajovic,Jakub Mensik,1536.300155,1521.392255,0,14.907901,2,2,0.501408,1
1248,20230612,Stuttgart,Grass,False,Lorenzo Musetti,Frances Tiafoe,1621.065878,1631.001373,0,-9.935495,0,0,0.501121,1
1313,20230529,Roland Garros,Clay,True,Fabio Fognini,Sebastian Ofner,1498.532631,1504.238342,0,-5.705712,0,0,0.501054,1
1701,20230206,Cordoba,Clay,False,Juan Pablo Varillas,Dusan Lajovic,1483.150140,1468.656542,0,14.493597,2,2,0.500820,1
1689,20230213,Rotterdam,Hard,False,Quentin Halys,Botic Van De Zandschulp,1520.279981,1506.344074,0,13.935907,2,2,0.500029,1

### player that caused most upsets

In [5]:
upsets_df['player_B_name'].value_counts().sort_values(ascending=False).reset_index()

             player_B_name  count
0            Zhizhen Zhang     11
1             Daniel Evans      9
2          Luca Van Assche      9
3         Marton Fucsovics      8
4            Stan Wawrinka      8
..                     ...    ...
159        Luciano Darderi      1
160  Stefanos Sakellaridis      1
161           Lloyd Harris      1
162          Zsombor Piros      1
163         Frances Tiafoe      1

[164 rows x 2 columns]

### player who was defeated most when expected to win

In [16]:
upsets_df['player_A_name'].value_counts().sort_values(ascending=False)

player_A_name
Stefanos Tsitsipas    12
Frances Tiafoe        11
Holger Rune           11
Taylor Fritz          10
Jiri Lehecka          10
                      ..
Jiri Vesely            1
Terence Atmane         1
Dominik Koepfer        1
Hugo Gaston            1
Jie Cui                1
Name: count, Length: 185, dtype: int64

In [22]:
upsets_df[upsets_df['player_A_name'] == 'Frances Tiafoe']

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
2759,20230828,Us Open,Hard,True,Frances Tiafoe,Ben Shelton,1647.788745,1473.055673,0,174.733072,2,2,0.839809,1
2791,20230731,Washington,Hard,False,Frances Tiafoe,Daniel Evans,1666.403791,1473.432617,0,192.971174,2,0,0.782187,1
2784,20230424,Madrid Masters,Clay,False,Frances Tiafoe,Pedro Cachin,1647.364311,1458.431940,0,188.932372,1,1,0.743389,1
2720,20230320,Miami Masters,Hard,False,Frances Tiafoe,Lorenzo Sonego,1627.088481,1474.078449,0,153.010032,2,2,0.687777,1
2719,20230807,Canada Masters,Hard,False,Frances Tiafoe,Milos Raonic,1654.590087,1502.074602,0,152.515485,2,2,0.687173,1
2384,20230814,Cincinnati Masters,Hard,False,Frances Tiafoe,Stan Wawrinka,1647.271023,1570.174193,0,77.096829,2,0,0.650343,1
2594,20230913,Davis Cup Finals RR: CRO vs USA,Hard,False,Frances Tiafoe,Borna Gojo,1651.398171,1535.761868,0,115.636303,2,2,0.640502,1
2630,20230417,Barcelona,Clay,False,Frances Tiafoe,Emil Ruusuvuori,1655.929684,1531.283704,0,124.645980,1,2,0.638242,1
2120,20230703,Wimbledon,Grass,True,Frances Tiafoe,Grigor Dimitrov,1674.721054,1628.302558,0,46.418496,0,0,0.627620,1
2183,20230206,Dallas,Hard,False,Frances Tiafoe,J J Wolf,1589.904579,1536.588018,0,53.316561,2,0,0.619052,1
2168,20230116,Australian Open,Hard,True,Frances Tiafoe,Karen Khachanov,1581.938512,1531.078885,0,50.859627,2,2,0.604974,1

In [17]:
shock_wins = df_filtered[df_filtered['predict_R'] == 0]
shock_wins

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
1251,20230417,Barcelona,Clay,False,Francisco Cerundolo,Casper Ruud,1545.164825,1554.828282,1,-9.663457,2,1,0.499258,0
1650,20230220,Doha,Hard,False,Andy Murray,Alexandre Muller,1525.561855,1513.892367,1,11.669488,0,1,0.499061,0
1673,20230109,Adelaide 2,Hard,False,Jason Kubler,Tomas Martin Etcheverry,1513.088544,1500.000000,1,13.088544,2,2,0.498826,0
895,20231016,Antwerp,Hard,False,Botic Van De Zandschulp,Dominic Stricker,1482.323340,1515.454093,1,-33.130752,2,0,0.498675,0
1291,20230703,Wimbledon,Grass,True,Jiri Lehecka,Tommy Paul,1589.691213,1596.568474,1,-6.877260,0,0,0.498144,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26,20230807,Canada Masters,Hard,False,Tommy Paul,Carlos Alcaraz,1599.815682,1871.224406,1,-271.408724,2,2,0.165204,0
31,20231002,Shanghai Masters,Hard,False,Diego Schwartzman,Taylor Fritz,1430.020839,1691.123998,1,-261.103159,1,2,0.164867,0
13,20230724,Hamburg,Clay,False,Daniel Altmaier,Andrey Rublev,1446.236069,1742.110979,1,-295.874910,1,1,0.155912,0
53,20230529,Roland Garros,Clay,True,Daniel Altmaier,Jannik Sinner,1458.158735,1690.906010,1,-232.747274,1,1,0.089383,0
18,20230529,Roland Garros,Clay,True,Thiago Seyboth Wild,Daniil Medvedev,1500.000000,1791.985524,1,-291.985524,1,1,0.051678,0

### prediction was for this player to have lost, but they won!

In [18]:
shock_wins['player_B_name'].value_counts().sort_values(ascending=False)

player_B_name
Sebastian Baez         13
Taylor Fritz           11
Stan Wawrinka          11
Tommy Paul             10
Nicolas Jarry           9
                       ..
Timofey Skatov          1
Luca Nardi              1
Eliot Spizzirri         1
Alexander Ritschard     1
Yoshihito Nishioka      1
Name: count, Length: 187, dtype: int64

### prediction was for this player to win, but they lost

In [19]:
shock_wins['player_A_name'].value_counts().sort_values(ascending=False)

player_A_name
Alexander Zverev           10
Alexander Bublik           10
Botic Van De Zandschulp     9
Roman Safiullin             9
Miomir Kecmanovic           9
                           ..
Mate Valkusz                1
Mitchell Krueger            1
Omni Kumar                  1
James Duckworth             1
Thiago Seyboth Wild         1
Name: count, Length: 168, dtype: int64

In [20]:
zverev_matches = df_filtered[(df_filtered['player_A_name'] == 'Alexander Bublik')]
zverev_matches[(zverev_matches['predict_R'] == 1) & (zverev_matches['player_A_win'] == 0)]

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
2577,20231106,Metz,Hard,False,Alexander Bublik,Fabio Fognini,1582.031620,1470.218929,0,111.812691,2,1,0.665243,1
1935,20230828,Us Open,Hard,True,Alexander Bublik,Dominic Thiem,1532.603859,1502.165324,0,30.438535,2,0,0.618972,1
2416,20230920,Chengdu,Hard,False,Alexander Bublik,Marcos Giron,1544.685761,1462.605603,0,82.080159,2,2,0.595566,1
922,20230306,Indian Wells Masters,Hard,False,Alexander Bublik,Tung Lin Wu,1454.967070,1485.594096,0,-30.627026,2,0,0.502229,1

How top players performed in five set matches

In [31]:
long_matches = df_filtered[(df_filtered['five_set'] == True) & (df_filtered['player_A_win'] == 1)]

In [32]:
long_matches['player_A_name'].value_counts()

player_A_name
Ben Shelton                    5
Jiri Lehecka                   4
Alexander Zverev               4
Roman Safiullin                3
Diego Schwartzman              3
                              ..
Yoshihito Nishioka             1
Lloyd Harris                   1
Alejandro Davidovich Fokina    1
Rinky Hijikata                 1
Thiago Seyboth Wild            1
Name: count, Length: 64, dtype: int64

### Analyzing 2024 data

In [33]:
df_2024 = pd.read_csv("analysis_with_surface_clusters_2024.csv")
df_2024

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
0,20230807,Canada Masters,Hard,False,Ben Shelton,Carlos Alcaraz,1410.848961,1864.117346,0,-453.268385,0,0,0.067122,0
1,20230814,Cincinnati Masters,Hard,False,Max Purcell,Carlos Alcaraz,1432.599522,1846.423679,0,-413.824157,0,0,0.082422,0
2,20230828,Us Open,Hard,True,Bernabe Zapata Miralles,Novak Djokovic,1458.760979,1857.668601,0,-398.907621,1,0,0.017960,0
3,20230828,Us Open,Hard,True,Lloyd Harris,Carlos Alcaraz,1464.366432,1852.334845,0,-387.968413,0,0,0.021697,0
4,20230828,Us Open,Hard,True,Alexandre Muller,Novak Djokovic,1481.946315,1860.411504,0,-378.465190,1,0,0.021772,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,20230828,Us Open,Hard,True,Novak Djokovic,Borna Gojo,1854.115400,1505.414043,1,348.701357,0,0,0.963284,1
2418,20230828,Us Open,Hard,True,Carlos Alcaraz,Daniel Evans,1848.794448,1499.381908,1,349.412541,0,1,0.969334,1
2419,20230703,Wimbledon,Grass,True,Carlos Alcaraz,Matteo Berrettini,1846.751562,1495.784060,1,350.967502,0,1,0.969775,1
2420,20230927,Beijing,Hard,False,Alexander Zverev,Diego Schwartzman,1771.926817,1415.766524,1,356.160293,0,1,0.890970,1
2421,20231123,Davis Cup Finals QF: SRB vs GBR,Hard,False,Novak Djokovic,Cameron Norrie,1915.192397,1513.517233,1,401.675164,0,0,0.898185,1

In [34]:
df_filtered_2024 = df_2024[df_2024['player_A_win'] != df_2024['predict_R']].sort_values(by='predict_proba_R', ascending=False)

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference,player_A_cluster,player_B_cluster,predict_proba_R,predict_R
26,20230619,Halle,Grass,False,Roberto Bautista Agut,Daniil Medvedev,1470.555041,1741.956835,1,-271.401794,0,1,0.193210,0
51,20231016,Tokyo,Hard,False,Shintaro Mochizuki,Taylor Fritz,1454.326910,1684.068809,1,-229.741900,1,0,0.188128,0
12,20230724,Hamburg,Clay,False,Daniel Altmaier,Andrey Rublev,1446.236069,1742.110979,1,-295.874910,1,2,0.186148,0
146,20230703,Wimbledon,Grass,True,Daniel Elahi Galan,Yoshihito Nishioka,1385.238609,1534.969629,1,-149.731020,0,0,0.179411,0
19,20230508,Rome Masters,Clay,False,Fabian Marozsan,Carlos Alcaraz,1500.037942,1783.473071,1,-283.435130,1,1,0.170123,0
29,20231002,Shanghai Masters,Hard,False,Diego Schwartzman,Taylor Fritz,1430.020839,1691.123998,1,-261.103159,1,0,0.162652,0
28,20230807,Canada Masters,Hard,False,Marcos Giron,Holger Rune,1471.700428,1732.899961,1,-261.199533,1,0,0.162579,0
25,20230807,Canada Masters,Hard,False,Tommy Paul,Carlos Alcaraz,1599.815682,1871.224406,1,-271.408724,1,0,0.154911,0
49,20230529,Roland Garros,Clay,True,Daniel Altmaier,Jannik Sinner,1458.158735,1690.906010,1,-232.747274,1,2,0.114404,0
17,20230529,Roland Garros,Clay,True,Thiago Seyboth Wild,Daniil Medvedev,1500.000000,1791.985524,1,-291.985524,1,1,0.057595,0

In [36]:
long_matches_2024 = df_filtered_2024[(df_filtered_2024['five_set'] == True) & (df_filtered_2024['player_A_win'] == 1)]
long_matches_2024['player_A_name'].value_counts()

player_A_name
Ben Shelton                    5
Ugo Humbert                    3
Diego Schwartzman              3
Alexander Zverev               3
Taro Daniel                    2
Jiri Lehecka                   2
Jakub Mensik                   2
Matteo Berrettini              2
Tomas Martin Etcheverry        2
Zhizhen Zhang                  2
Juan Pablo Varillas            2
Roman Safiullin                2
Christopher Eubanks            1
Sebastian Ofner                1
Matteo Arnaldi                 1
Stefanos Tsitsipas             1
Emil Ruusuvuori                1
Lorenzo Musetti                1
Yu Hsiou Hsu                   1
Lloyd Harris                   1
Hubert Hurkacz                 1
Botic Van De Zandschulp        1
Gael Monfils                   1
Rafael Nadal                   1
Novak Djokovic                 1
Jan Choinski                   1
David Goffin                   1
Titouan Droguet                1
Daniil Medvedev                1
Daniel Elahi Galan             1
Daniel Altmaier                1
Casper Ruud                    1
Yoshihito Nishioka             1
Rinky Hijikata                 1
Arthur Rinderknech             1
Yosuke Watanuki                1
Felix Auger Aliassime          1
Dalibor Svrcina                1
Thiago Agustin Tirante         1
Jack Draper                    1
Marton Fucsovics               1
Alexander Bublik               1
Nicolas Jarry                  1
Christopher Oconnell           1
Taylor Fritz                   1
Tommy Paul                     1
Bernabe Zapata Miralles        1
Thanasi Kokkinakis             1
Denis Shapovalov               1
Francisco Cerundolo            1
Stan Wawrinka                  1
Grigor Dimitrov                1
Mackenzie Mcdonald             1
Aleksandar Vukic               1
Alejandro Davidovich Fokina    1
Thiago Seyboth Wild            1
Name: count, dtype: int64