In [1]:
import pandas as pd
from collections import defaultdict

In [11]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

# show all columns
pd.set_option("display.max_columns", None)

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [12]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [13]:
%%R

require('tidyverse')
require('DescTools')

In [18]:
import glob
import pandas as pd

csv_files = glob.glob("/Users/hazelgandhi/Desktop/tennis-regression/files/*.csv")

df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)

In [19]:
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2023-9900,United Cup,Hard,18,A,20230102,300,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,7-6(4) 7-6(6),3,F,135.0,15.0,2.0,85.0,52.0,45.0,16.0,12.0,0.0,0.0,7.0,2.0,97.0,62.0,47.0,15.0,12.0,9.0,9.0,9.0,3355.0,16.0,2375.0
1,2023-9900,United Cup,Hard,18,A,20230102,299,126207,NaN,NaN,Frances Tiafoe,R,188.0,USA,24.9,207518,NaN,NaN,Lorenzo Musetti,R,185.0,ITA,20.8,6-2 0-0 RET,3,F,34.0,3.0,1.0,27.0,19.0,15.0,3.0,4.0,3.0,3.0,0.0,0.0,21.0,12.0,8.0,3.0,4.0,1.0,3.0,19.0,2000.0,23.0,1865.0
2,2023-9900,United Cup,Hard,18,A,20230102,296,126203,3.0,NaN,Taylor Fritz,R,196.0,USA,25.1,128034,2.0,NaN,Hubert Hurkacz,R,196.0,POL,25.8,7-6(5) 7-6(5),3,SF,104.0,11.0,0.0,80.0,50.0,44.0,19.0,12.0,4.0,4.0,17.0,1.0,82.0,62.0,51.0,7.0,12.0,2.0,2.0,9.0,3355.0,10.0,2905.0
3,2023-9900,United Cup,Hard,18,A,20230102,295,126207,NaN,NaN,Frances Tiafoe,R,188.0,USA,24.9,200390,NaN,NaN,Kacper Zuk,R,183.0,POL,23.9,6-3 6-3,3,SF,79.0,5.0,4.0,61.0,37.0,31.0,11.0,9.0,5.0,5.0,3.0,3.0,68.0,41.0,26.0,12.0,9.0,6.0,9.0,19.0,2000.0,245.0,220.0
4,2023-9900,United Cup,Hard,18,A,20230102,292,126774,1.0,NaN,Stefanos Tsitsipas,R,193.0,GRE,24.3,126610,5.0,NaN,Matteo Berrettini,R,196.0,ITA,26.7,4-6 7-6(2) 6-4,3,SF,155.0,9.0,1.0,98.0,52.0,43.0,28.0,16.0,1.0,2.0,7.0,2.0,89.0,58.0,48.0,18.0,16.0,1.0,2.0,4.0,5550.0,16.0,2375.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5898,2022-M-DC-2022-WG2-PO-GRE-JAM-01,Davis Cup WG2 PO: GRE vs JAM,Clay,4,D,20220304,4,209362,NaN,NaN,Aristotelis Thanos,R,NaN,GRE,20.8,209080,NaN,NaN,Blaise Bicknell,R,191.0,JAM,20.2,6-4 6-4,3,RR,115.0,0.0,4.0,70.0,48.0,35.0,12.0,10.0,5.0,5.0,1.0,3.0,96.0,68.0,42.0,12.0,10.0,11.0,13.0,1103.0,9.0,1130.0,8.0
5899,2022-M-DC-2022-WG2-PO-GRE-JAM-01,Davis Cup WG2 PO: GRE vs JAM,Clay,4,D,20220304,5,202065,NaN,NaN,Petros Tsitsipas,R,185.0,GRE,21.5,202120,NaN,NaN,Rowland Phillips,R,NaN,JAM,28.0,4-6 6-4 6-4,3,RR,161.0,7.0,2.0,94.0,55.0,37.0,23.0,15.0,9.0,12.0,1.0,1.0,94.0,56.0,40.0,20.0,15.0,4.0,8.0,808.0,23.0,1390.0,4.0
5900,2022-M-DC-2022-WG2-PO-HKG-BEN-01,Davis Cup WG2 PO: HKG vs BEN,Hard,4,D,20220304,1,138846,NaN,NaN,Hong Kit Jack Wong,R,NaN,HKG,23.4,105278,NaN,NaN,Alexis Klegou,U,NaN,BEN,33.0,1-6 6-4 4-1 RET,3,RR,250.0,4.0,8.0,56.0,33.0,20.0,13.0,11.0,3.0,7.0,0.0,3.0,72.0,54.0,29.0,8.0,11.0,6.0,10.0,1059.0,10.0,1881.0,1.0
5901,2022-M-DC-2022-WG2-PO-HKG-BEN-01,Davis Cup WG2 PO: HKG vs BEN,Hard,4,D,20220304,2,209409,NaN,NaN,Coleman Wong,R,191.0,HKG,17.7,200583,NaN,NaN,Delmas Ntcha,R,NaN,BEN,21.7,6-4 6-4,3,RR,98.0,2.0,2.0,68.0,38.0,24.0,18.0,10.0,6.0,8.0,1.0,5.0,58.0,39.0,24.0,7.0,10.0,5.0,9.0,1050.0,10.0,NaN,NaN
5902,2022-M-DC-2022-WG2-PO-HKG-BEN-01,Davis Cup WG2 PO: HKG vs BEN,Hard,4,D,20220304,4,208414,NaN,NaN,Sylvestre Monnou,R,NaN,BEN,19.2,207132,NaN,NaN,Ki Lung Ng,R,NaN,HKG,20.5,6-4 6-4,3,RR,92.0,5.0,5.0,70.0,32.0,28.0,17.0,10.0,4.0,5.0,6.0,2.0,60.0,34.0,24.0,13.0,10.0,5.0,8.0,NaN,NaN,NaN,NaN

In [20]:
# Load match data
df = df.sort_values('tourney_date')

five_set = ['Us Open','Roland Garros', 'Australian Open', 'Wimbledon']
df['five_set'] = df.tourney_name.isin(five_set)


# Initialize Elo ratings
elo_ratings = defaultdict(lambda: 1500)

# Store Elo snapshot *before* each match
elo_snapshots = []

K = 30

def win_prob(rating_i, rating_j):
    return 1 / (1 + 10 ** ((rating_j - rating_i) / 400))

for _, match in df.iterrows():
    winner = match['winner_name']
    loser = match['loser_name']

    rating_winner = elo_ratings[winner]
    rating_loser = elo_ratings[loser]

    # Record pre-match Elo ratings
    elo_snapshots.append({
        'date': match['tourney_date'],
        'surface': match['surface'],
        'tournament': match['tourney_name'],
        'winner': winner,
        'loser': loser,
        'five_set': match['five_set'],
        'winner_elo_before': rating_winner,
        'loser_elo_before': rating_loser
    })

    # Calculate expected outcomes
    expected_win = win_prob(rating_winner, rating_loser)
    expected_loss = 1 - expected_win

    # Update ratings
    elo_ratings[winner] += K * (1 - expected_win)
    elo_ratings[loser] += K * (0 - expected_loss)

# Create DataFrame
elo_df = pd.DataFrame(elo_snapshots)
elo_df

,date,surface,tournament,winner,loser,five_set,winner_elo_before,loser_elo_before
0,20220103,Hard,Atp Cup,Felix Auger Aliassime,Roberto Bautista Agut,False,1500.000000,1500.000000
1,20220103,Hard,Adelaide 1,Gianluca Mager,Francisco Cerundolo,False,1500.000000,1500.000000
2,20220103,Hard,Adelaide 1,Egor Gerasimov,Marton Fucsovics,False,1500.000000,1500.000000
3,20220103,Hard,Adelaide 1,Thiago Monteiro,Daniel Altmaier,False,1500.000000,1500.000000
4,20220103,Hard,Adelaide 1,Corentin Moutet,Holger Rune,False,1500.000000,1500.000000
...,...,...,...,...,...,...,...,...
5898,20231127,Hard,NextGen Finals,Arthur Fils,Dominic Stricker,False,1594.446414,1549.788190
5899,20231127,Hard,NextGen Finals,Hamad Medjedovic,Dominic Stricker,False,1531.638967,1536.705692
5900,20231127,Hard,NextGen Finals,Arthur Fils,Luca Van Assche,False,1607.528912,1495.366613
5901,20231127,Hard,NextGen Finals,Hamad Medjedovic,Abedallah Shelbayh,False,1546.857700,1457.038529
5902,20231127,Hard,NextGen Finals,Hamad Medjedovic,Arthur Fils,False,1558.064034,1617.847971

In [21]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Randomly assign winner to be Player A or B
winner_is_A = np.random.randint(0, 2, size=len(elo_df)) == 1

# Create transformed DataFrame
elo_transformed = pd.DataFrame({
    'date': elo_df['date'],
    'tournament': elo_df['tournament'],
    'surface' : elo_df['surface'],
    'five_set': elo_df['five_set'],
    'player_A_name': np.where(winner_is_A, elo_df['winner'], elo_df['loser']),
    'player_B_name': np.where(winner_is_A, elo_df['loser'], elo_df['winner']),
    
    'player_A_elo_before': np.where(winner_is_A, elo_df['winner_elo_before'], elo_df['loser_elo_before']),
    'player_B_elo_before': np.where(winner_is_A, elo_df['loser_elo_before'], elo_df['winner_elo_before']),
    
    'player_A_win': winner_is_A.astype(int)
})
elo_transformed

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win
0,20220103,Atp Cup,Hard,False,Roberto Bautista Agut,Felix Auger Aliassime,1500.000000,1500.000000,0
1,20220103,Adelaide 1,Hard,False,Gianluca Mager,Francisco Cerundolo,1500.000000,1500.000000,1
2,20220103,Adelaide 1,Hard,False,Marton Fucsovics,Egor Gerasimov,1500.000000,1500.000000,0
3,20220103,Adelaide 1,Hard,False,Daniel Altmaier,Thiago Monteiro,1500.000000,1500.000000,0
4,20220103,Adelaide 1,Hard,False,Holger Rune,Corentin Moutet,1500.000000,1500.000000,0
...,...,...,...,...,...,...,...,...,...
5898,20231127,NextGen Finals,Hard,False,Dominic Stricker,Arthur Fils,1549.788190,1594.446414,0
5899,20231127,NextGen Finals,Hard,False,Dominic Stricker,Hamad Medjedovic,1536.705692,1531.638967,0
5900,20231127,NextGen Finals,Hard,False,Arthur Fils,Luca Van Assche,1607.528912,1495.366613,1
5901,20231127,NextGen Finals,Hard,False,Hamad Medjedovic,Abedallah Shelbayh,1546.857700,1457.038529,1
5902,20231127,NextGen Finals,Hard,False,Hamad Medjedovic,Arthur Fils,1558.064034,1617.847971,1

In [22]:
elo_transformed['elo_difference'] = elo_transformed['player_A_elo_before'] - elo_transformed ['player_B_elo_before']
elo_transformed

,date,tournament,surface,five_set,player_A_name,player_B_name,player_A_elo_before,player_B_elo_before,player_A_win,elo_difference
0,20220103,Atp Cup,Hard,False,Roberto Bautista Agut,Felix Auger Aliassime,1500.000000,1500.000000,0,0.000000
1,20220103,Adelaide 1,Hard,False,Gianluca Mager,Francisco Cerundolo,1500.000000,1500.000000,1,0.000000
2,20220103,Adelaide 1,Hard,False,Marton Fucsovics,Egor Gerasimov,1500.000000,1500.000000,0,0.000000
3,20220103,Adelaide 1,Hard,False,Daniel Altmaier,Thiago Monteiro,1500.000000,1500.000000,0,0.000000
4,20220103,Adelaide 1,Hard,False,Holger Rune,Corentin Moutet,1500.000000,1500.000000,0,0.000000
...,...,...,...,...,...,...,...,...,...,...
5898,20231127,NextGen Finals,Hard,False,Dominic Stricker,Arthur Fils,1549.788190,1594.446414,0,-44.658223
5899,20231127,NextGen Finals,Hard,False,Dominic Stricker,Hamad Medjedovic,1536.705692,1531.638967,0,5.066725
5900,20231127,NextGen Finals,Hard,False,Arthur Fils,Luca Van Assche,1607.528912,1495.366613,1,112.162299
5901,20231127,NextGen Finals,Hard,False,Hamad Medjedovic,Abedallah Shelbayh,1546.857700,1457.038529,1,89.819170
5902,20231127,NextGen Finals,Hard,False,Hamad Medjedovic,Arthur Fils,1558.064034,1617.847971,1,-59.783937

In [23]:
# Rename for merging with player A and player B
cluster_A = surface_clustered.rename(columns={
    'player_name': 'player_A_name',
    'cluster': 'player_A_cluster'
})

cluster_B = surface_clustered.rename(columns={
    'player_name': 'player_B_name',
    'cluster': 'player_B_cluster'
})

NameError: name 'surface_clustered' is not defined